version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus-configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-configs:/etc/prometheus/alerts
    # command:
    #   - '--config.file=/etc/prometheus/prometheus.yml'
    #   - '--storage.tsdb.path=/prometheus'
    #   - '--web.console.libraries=/usr/share/prometheus/console_libraries'
    #   - '--web.console.templates=/usr/share/prometheus/consoles'

    ports:
      - "9090:9090"
  # prometheus:
  #   image: prom/prometheus:v2.30.3
  #   ports:
  #     - 9090:9090
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:8.2.1
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

  proxy-manager:
    image: justmark0/proxymanager:latest
    ports:
      - '8000:8000'
    network_mode: "host"

  proxymanager-front:
    image: justmark0/proxymanager-front:latest
    ports:
      - 80:3000

volumes:
  grafana-data:
