version: '3.8'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.2
    volumes:
      - ./logstash-config:/usr/share/logstash/config
      - ./logstash-pipeline:/usr/share/logstash/pipeline

      - /var/lib/docker/containers/a90b3899aacd/a90b3899aacd-json.log:/logs/log:ro
    networks:
      - elk

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms700m -Xmx700m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata762a1b0b-5ba2-4856-9adf-38cb7752c0dd:/usr/share/elasticsearch/data
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    ports:
      - "5601:5601"
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  esdata762a1b0b-5ba2-4856-9adf-38cb7752c0dd:
